### ISSUE TITLE
crashes if $EDITOR contains a space

### ISSUE THREAD

**Issue by reidpr** [Genzer/todo.txt-note#1]
Hi, thanks for this!

Currently it crashes if `$EDITOR` contains a space:

```
$ echo $EDITOR
emacs -nw
$ td note add 1
Traceback (most recent call last):
  File "/Users/reidpr/.todo/actions.d/note/note.py", line 216, in <module>
    main(sys.argv[1:])
  File "/Users/reidpr/.todo/actions.d/note/note.py", line 212, in main
    parsed_args.func(**input)
  File "/Users/reidpr/.todo/actions.d/note/note.py", line 122, in add_note
    return_code = call([editor, note_file])
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'emacs -nw'
```

**Comment by reidpr** [comment]
So I looked into this a little more and there's not 100% agreement on whether `$EDITOR` can contain arguments. For example, zsh also refuses them in the same way. But, there is a lot of advice to set `EDITOR='emacs -nw'` on the web. And `subprocess` does give advice to avoid the shell when possible. So, I am not sure what the correct behavior here is.

**Comment by Genzer** [comment]
Hi @reidpr,

I could quickly resolve this issue via PR #4 . I tested on my environment using `EDITOR="vim --noplugin"`. Could you also have a look whether it solves your case as well?

Thanks!
